### ISSUE TITLE
Can't create an extension as documented

### ISSUE THREAD

**Issue by thorrr** [pyscaffold/pyscaffold#221]
## putup with documented arguments to bootstrap an extension doesn't work

**Please provide a minimal, self-contained, and reproducible example.**

```sh 
$ putup pyscaffoldext-abc -p abc --namespace pyscaffoldext --no-skeleton
Traceback (most recent call last):
  File "/home/user/projects/pyscaffold/env/bin/putup", line 11, in <module>
    load_entry_point('PyScaffold', 'console_scripts', 'putup')()
  File "/home/user/projects/pyscaffold/src/pyscaffold/shell.py", line 74, in func_wrapper
    func(*args, **kwargs)
  File "/home/user/projects/pyscaffold/src/pyscaffold/utils.py", line 159, in func_wrapper
    func(*args, **kwargs)
  File "/home/user/projects/pyscaffold/src/pyscaffold/cli.py", line 206, in run
    main(sys.argv[1:])
  File "/home/user/projects/pyscaffold/src/pyscaffold/cli.py", line 199, in main
    opts['command'](opts)
  File "/home/user/projects/pyscaffold/src/pyscaffold/cli.py", line 171, in run_scaffold
    api.create_project(opts)
  File "/home/user/projects/pyscaffold/src/pyscaffold/api/__init__.py", line 301, in create_project
    return reduce(lambda acc, f: _invoke(f, *acc), actions, ({}, opts))
  File "/home/user/projects/pyscaffold/src/pyscaffold/api/__init__.py", line 301, in <lambda>
    return reduce(lambda acc, f: _invoke(f, *acc), actions, ({}, opts))
  File "/home/user/projects/pyscaffold/src/pyscaffold/api/__init__.py", line 319, in _invoke
    struct, opts = action(struct, opts)
  File "/home/user/projects/pyscaffold/src/pyscaffold/extensions/namespace.py", line 115, in add_namespace
    struct = base_struct[opts['project']]['src']
KeyError: 'src'
```
## Versions and main components

* PyScaffold Version:  master, 3.1.4, 3.1.0 
* Python Version: 3.6.7
* Operating system: Ubuntu 18
* How did you install PyScaffold: (conda/pip)  pip from git repo

**Comment by thorrr** [comment]
Looks like tag v3.0.2 works without errors.  v3.1.0 and v3.1.4 breaks for me.

**Comment by thorrr** [comment]
You're right - closing this.  It's contaminated by some old pyscaffold versions I had pip installed.  Apologies for the confusion!
