### ISSUE TITLE
Pyscaffold v4.1.0 cannot handle comments in setup.cfg install_requires section

### ISSUE THREAD

**Issue by mhaley-tignis** [pyscaffold/pyscaffold#516]
## Description of your problem
With pyscaffold v4.0.2 we could have comments in our install_requires section like below

**Please provide a minimal, self-contained, and reproducible example.**
setup.cfg
```python
install_requires =
    importlib-metadata; python_version<"3.8"
#Adding some comments here that are perfectly valid.
    some-other-dependency
```
Running `putup -vv --update test-app` results in the following

**Please provide the full traceback.**
```python
Traceback (most recent call last):
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/api.py", line 177, in _read_existing_config
    opts = info.project(opts)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/info.py", line 180, in project
    cfg = read_setupcfg(path, config_file).to_dict()
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/info.py", line 256, in read_setupcfg
    updater.read(path, encoding="utf-8")
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/configupdater/configupdater.py", line 122, in read
    return self._parser().read(filename, encoding, self)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/configupdater/parser.py", line 239, in read
    self._read(fp, filename, document)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/configupdater/parser.py", line 453, in _read
    self._add_option_line(line)  # HOOK
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/configupdater/parser.py", line 364, in _add_option_line
    raise InconsistentStateError(msg, self._fpname, self._lineno, line)
configupdater.parser.InconsistentStateError: <Comment: '#Adding some comments here that are perfectly valid.\n'> should be Option or Space
test-app/setup.cfg(51): '    some-other-dependency\n'
```

Changing the section to be like
```
install_requires =
    importlib-metadata; python_version<"3.8"
    #Adding some comments here that are perfectly valid.
    some-other-dependency
```

Results in 
```
Traceback (most recent call last):
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...), found '#'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mhaley/.pyenv/versions/aipc-devtool/bin/putup", line 8, in <module>
    sys.exit(run())
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/shell.py", line 113, in func_wrapper
    func(*args, **kwargs)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/exceptions.py", line 33, in func_wrapper
    func(*args, **kwargs)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/cli.py", line 263, in run
    main(args or sys.argv[1:])
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/cli.py", line 256, in main
    opts["command"](opts)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/cli.py", line 225, in run_scaffold
    api.create_project(opts)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/api.py", line 156, in create_project
    return reduce(actions.invoke, pipeline, ({}, opts))
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/actions.py", line 98, in invoke
    return action(*struct_and_opts)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/update.py", line 66, in version_migration
    return reduce(invoke, plan_actions, (struct, opts))
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/actions.py", line 98, in invoke
    return action(*struct_and_opts)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/update.py", line 75, in _wrapped
    setupcfg, opts = fn(setupcfg, opts)
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/update.py", line 126, in add_dependencies
    install_requires = deps.add(deps.RUNTIME, deps.split(install_requires.value))
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/dependencies.py", line 68, in add
    return deduplicate(chain(requirements, to_add))
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/dependencies.py", line 54, in deduplicate
    return list({Requirement(r).name: r for r in requirements}.values())
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/pyscaffold/dependencies.py", line 54, in <dictcomp>
    return list({Requirement(r).name: r for r in requirements}.values())
  File "/Users/mhaley/.pyenv/versions/3.8.7/envs/aipc-devtool/lib/python3.8/site-packages/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'#Adding '": Expected W:(abcd...)
```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 4.1
* Python Version: 3.8.7
* Operating system: MacOS
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Thank you very much @mhaley-tignis, I released an RC with the fix we have discussed and your contributions: https://pypi.org/project/PyScaffold/4.1.1rc2/
