### ISSUE TITLE
config option long-description missing?

### ISSUE THREAD

**Issue by zirpu** [pyscaffold/pyscaffold#631]
## Description of your problem

When using 'putup -i proj' it fails looking for a 'long-description' key in the config.

**Please provide the full traceback using the `--very-verbose` flag.**
```python
$ putup -i map2map_quiz
    activate  pyscaffold.extensions.config
    activate  pyscaffold.extensions.gitlab_ci
    activate  pyscaffold.extensions.pre_commit
    activate  pyscaffoldext.markdown.extension
      invoke  pyscaffold.actions:get_default_options
       check    is git installed...
         run    git --version
       check    is git configured...
         run    git config --get user.name
         run    git config --get user.email
         run    git config --get user.name
         run    git config --get user.email
      invoke  pyscaffold.actions:verify_options_consistency
      invoke  pyscaffold.structure:define_structure
      invoke  pyscaffoldext.markdown.extension:add_doc_requirements
      invoke  pyscaffold.extensions.pre_commit:find_executable
      invoke  pyscaffold.extensions.pre_commit:add_files
      invoke  pyscaffold.extensions.gitlab_ci:add_files
      invoke  pyscaffoldext.markdown.extension:replace_files
Traceback (most recent call last):
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/configupdater/section.py", line 138, in __getitem__
    return next(o for o in self.iter_options() if o.key == key)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/allan/.local/bin/putup", line 8, in <module>
    sys.exit(run())
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/shell.py", line 133, in func_wrapper
    func(*args, **kwargs)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/exceptions.py", line 34, in func_wrapper
    func(*args, **kwargs)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/cli.py", line 263, in run
    main(args or sys.argv[1:])
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/cli.py", line 256, in main
    opts["command"](opts)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/extensions/interactive.py", line 125, in command
    cli.main(split_args(content))  # Call the CLI again with the new options
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/cli.py", line 256, in main
    opts["command"](opts)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/cli.py", line 225, in run_scaffold
    api.create_project(opts)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/api.py", line 156, in create_project
    return reduce(actions.invoke, pipeline, ({}, opts))
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffold/actions.py", line 99, in invoke
    return action(*struct_and_opts)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffoldext/markdown/extension.py", line 122, in replace_files
    struct["setup.cfg"] = (add_long_desc(content), file_op)
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/pyscaffoldext/markdown/extension.py", line 41, in add_long_desc
    metadata["long-description"].value = "file: README.md"
  File "/home/allan/.local/pipx/venvs/pyscaffold/lib/python3.8/site-packages/configupdater/section.py", line 140, in __getitem__
    raise KeyError(f"No option `{key}` found", {"key": key}) from ex
KeyError: ('No option `long-description` found', {'key': 'long-description'})

```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 4.2.1
* Python Version: 3.8.10
* Operating system: linux
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Hi @zirpu thank you very much for reporting this. I will have a look as soon as I can.

Meanwhile can you try to update PyScaffold and all its dependencies (I see you use the markdown one) to the latest version, just to see if the issue persists?

**Comment by zirpu** [comment]
Thanks.  That was it.  I had initially had it installed via pipx but w/o the [all] spec.  Works now.
