### ISSUE TITLE
Error when migrating to pyscaffold

### ISSUE THREAD

**Issue by ofosos** [pyscaffold/pyscaffold#648]
## Description of your problem

I get an error, when trying to migrate to pyscaffold. It looks like pyscaffold tries to look up some library directory that is empty, instead of looking into the distributed source directory (where the default.cfg resides?).

**Please provide a minimal, self-contained, and reproducible example.**
```bash
# git clone https://codeberg.org/ofosos/rotoscope
# git checkout 9aa1d2f
# ./rotoscope/venv/bin/putup rotoscope --force --no-skeleton -n rotoscope -d 'Move some files around. Bleep. Bloop.' -l GLWT -u http://codeberg.org/ofosos/rotoscope --save-config --pre-commit --markdown
```

**Please provide the full traceback using the `--very-verbose` flag.**
```python
Traceback (most recent call last):
  File "./rotoscope/venv/bin/putup", line 8, in <module>
    sys.exit(run())
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/shell.py", line 133, in func_wrapper
    func(*args, **kwargs)
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/exceptions.py", line 34, in func_wrapper
    func(*args, **kwargs)
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/cli.py", line 263, in run
    main(args or sys.argv[1:])
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/cli.py", line 256, in main
    opts["command"](opts)
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/cli.py", line 225, in run_scaffold
    api.create_project(opts)
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/api.py", line 156, in create_project
    return reduce(actions.invoke, pipeline, ({}, opts))
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/actions.py", line 99, in invoke
    return action(*struct_and_opts)
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/extensions/config.py", line 88, in save
    operations.create(file, str(config), opts)  # operations provide logging and pretend
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/operations.py", line 103, in create
    return fs.create_file(path, contents, pretend=opts.get("pretend"))
  File "/Users/mark/PycharmProjects/rotoscope/venv/lib/python3.8/site-packages/pyscaffold/file_system.py", line 102, in create_file
    path.write_text(content, encoding=encoding)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1254, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mark/Library/Preferences/pyscaffold/default.cfg'
```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 4.2.2
* Python Version: 3.8
* Operating system: Mac OS 12.4 / Apple Silicon
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Thank you very much for reporting this issue @ofosos.
It would seem that I might have forgotten to create the directory before writing the file...

Sorry for the disruption 😅. I will provide a patch soon.

Meanwhile if you want to keep playing with PyScaffold, I have the impression that if you create the `/Users/mark/Library/Preferences/pyscaffold/` repository, things may work...

**Comment by abravalheri** [comment]
The new version 4.2.3 should be out with a fix for this problem :)
