### ISSUE TITLE
TypeError: 'NoneType' object is not callable (Putup)

### ISSUE THREAD

**Issue by AaronCanty** [pyscaffold/pyscaffold#712]
## Description of your problem
Hi all,

Looking to create a python package with pyscaffold and putup, and there's no issue when I first use 
`pip install pyscaffold tox pyscaffoldext-markdown`, 
but when I then follow up with `putup -f --markdown --no-skeleton -n myProject .    `     

I end up with:

_TypeError: 'NoneType' object is not callable_

**Please provide the full traceback using the `--very-verbose` flag.**

```

(base) C:\Users\acanty\OneDrive - JNJ\Documents\Python Scripts>putup -f --markdown --no-skeleton -n myProject . --very-verbose
activate  pyscaffold.extensions.no_skeleton
activate  pyscaffoldext.markdown.extension
invoke  pyscaffold.actions:get_default_options
check    is git installed... 
run    git.exe –version
info    last command failed with "'git.exe' is not recognized as an internal or external command, 
operable program or batch file."
run    git.exe –version
info    last command failed with "The system cannot find the file specified: None"
Traceback (most recent call last):File "C:\Users\acanty\AppData\Local\anaconda3\lib\runpy.py", line 196, in _run_module_as_main 
return _run_code(code, main_globals, None,
File "C:\Users\acanty\AppData\Local\anaconda3\lib\runpy.py", line 86, in _run_code
exec(code, run_globals) 
File "C:\Users\acanty\AppData\Local\anaconda3\Scripts\putup.exe\__main__.py", line 7, in <module>
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\shell.py", line 133, in func_wrapper
func(*args, **kwargs)
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\exceptions.py", line 34, in func_wrapper
func(*args, **kwargs)
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\cli.py", line 263, in run main(args or sys.argv[1:])
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\cli.py", line 256, in main
opts["command"](opts)
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\cli.py", line 225, in run_scaffold
api.create_project(opts)
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\api.py", line 156, in create_project
return reduce(actions.invoke, pipeline, ({}, opts))
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\actions.py", line 99, in invoke
return action(*struct_and_opts)
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\actions.py", line 222, in get_default_options
info.check_git()
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\info.py", line 127, in check_git
if not is_git_installed():
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\info.py", line 92, in is_git_installed
shell.git("--version")
File "C:\Users\acanty\AppData\Local\anaconda3\lib\site-packages\pyscaffold\shell.py", line 267, in git 
return get_git_cmd()(*args, **kwargs)
TypeError: 'NoneType' object is not callable


```

**Please provide any additional information below.**

I'm running Windows 10 on an Anaconda shell. I have uninstalled and reinstalled pip & pyscaffold but even just the command `putup` gives me the NoneType error. 

Anyone else having the same issue?

Thanks!

**Comment by FlorianWilhelm** [comment]
Hi @AaronCanty, it seems that PyScaffold can't find `git.exe`, maybe it's not in your PATH? Does git work in your shell?
